// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCS6rFwR6tVwkh9JxpKQVG648HWLeUuv0',
    appId: '1:443390177253:web:606691bc8cd9a8f741c90c',
    messagingSenderId: '443390177253',
    projectId: 'food-delivery-88856',
    authDomain: 'food-delivery-88856.firebaseapp.com',
    storageBucket: 'food-delivery-88856.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKDx5HPQZ770WE_Ih-dFd7TIIhOudp8DM',
    appId: '1:443390177253:android:ebcc9f41b25ea4c641c90c',
    messagingSenderId: '443390177253',
    projectId: 'food-delivery-88856',
    storageBucket: 'food-delivery-88856.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh1N5cTyKQ9Mx7WfKhjF1Q_oywGUL3wlM',
    appId: '1:443390177253:ios:7744dadcc5b2ad4741c90c',
    messagingSenderId: '443390177253',
    projectId: 'food-delivery-88856',
    storageBucket: 'food-delivery-88856.firebasestorage.app',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh1N5cTyKQ9Mx7WfKhjF1Q_oywGUL3wlM',
    appId: '1:443390177253:ios:7744dadcc5b2ad4741c90c',
    messagingSenderId: '443390177253',
    projectId: 'food-delivery-88856',
    storageBucket: 'food-delivery-88856.firebasestorage.app',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCS6rFwR6tVwkh9JxpKQVG648HWLeUuv0',
    appId: '1:443390177253:web:9808b832ff013d8541c90c',
    messagingSenderId: '443390177253',
    projectId: 'food-delivery-88856',
    authDomain: 'food-delivery-88856.firebaseapp.com',
    storageBucket: 'food-delivery-88856.firebasestorage.app',
  );
}
